# fly.toml app configuration file generated for report-bug on 2023-10-11T20:37:16-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "report-bug"
primary_region = "scl"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
